version: "3"
services:
  abn-recipes:
    container_name: abn-recipes
    image: latest/abn-recipes
    restart: always
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'